version: "3"

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: twitter_clone
    ports:
      - "5435:5432"
  test_db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: twitter_clone_test
  web:
    build: ./docker_dev
    command: ./scripts/entrypoint.dev.sh
    volumes:
      - ".:/code"
    ports:
      - "4000:4000"
    depends_on:
      - postgres
      - test_db
      - redis